# -*- coding: utf-8 -*-
"""phase3_calculate_phenoage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ir1u2OylXHtHO4E7AjpzBcefHa7PPgHQ
"""

import numpy as np
import pandas as pd
import os

print("=" * 60)
print("COMBINED PHASE 2 & PHASE 3: PHENOAGE COMPUTATION (FINAL CORRECTED)")
print("=" * 60)

INPUT_CSV = "/content/bridge-ai-summit/Data/merged_nhanes_2015_2016_with_mortality.csv"
OUTPUT_CSV = "/content/bridge-ai-summit/Data/phenoage_completed_phase3.csv"

if not os.path.exists(INPUT_CSV):
    print(f"Error: ไม่พบไฟล์ {INPUT_CSV}")
else:
    df = pd.read_csv(INPUT_CSV)
    print(f"Loaded dataset: {len(df):,} rows")

    # เฟส 2: สร้าง Target
    df["mortality_10yr"] = df["died_10yr"]
    df["follow_up_months"] = df["PERMTH_INT"]

    # ── 🛠️ SCIENTIFIC UNIT RE-ALIGNMENT ──

    # 1. ปรับสเกล Glucose: แปลงจาก mg/dL กลับไปเป็น mmol/L เพื่อไม่ให้พจน์ xb ระเบิดล้น
    glucose_mmol_l = df['glucose'] / 18.0

    # 2. ปรับสเกล CRP: หาร 10 กลับคืนมา เนื่องจากข้อมูลในเวอร์ชัน 2015-2016 เป็น mg/L อยู่แล้ว
    crp_real = df['crp_mgl'] / 10.0
    crp_clean = np.where(crp_real <= 0, 0.001, crp_real)
    ln_crp = np.log(crp_clean)

    # 3. ปรับสเกล Lymphocyte: แปลงจาก % ให้กลายเป็น Absolute Count (10³ cells/µL)
    lymph_absolute = (df['wbc'] * df['lymph_pct']) / 100.0

    # Step 1: คำนวณ xb ด้วยสเกลหน่วยที่ถูกต้องแม่นยำ
    df['xb'] = (
        -19.907
        - 0.0336  * df['albumin']
        + 0.0095  * df['creatinine']
        + 0.1953  * glucose_mmol_l     # ใช้หน่วย mmol/L ตัวเลขจะอยู่ที่ ~5-6
        + 0.0954  * ln_crp
        - 0.0120  * lymph_absolute
        + 0.0268  * df['mcv']
        + 0.3306  * df['rdw']
        + 0.00188 * df['alp']
        + 0.0554  * df['wbc']
        + 0.0804  * df['age']
    )

    # Step 2: คำนวณ Mortality Score (M)
    raw_M = 1 - np.exp(-1.51714 * np.exp(df['xb']) / 0.0076927)
    df['M'] = np.clip(raw_M, 0.0001, 0.9999)

    # Step 3: แปลงเป็นอายุชีวภาพ PhenotypicAge
    df['PhenotypicAge'] = 141.50 + (np.log(-0.00553 * np.log(1 - df['M'])) / 0.09165)
    df['PhenoAge_gap'] = df['PhenotypicAge'] - df['age']

    # ตรวจเช็คเคสผิดปกติ
    implausible_mask = (df['PhenotypicAge'] < 0) | (df['PhenotypicAge'] > 150)
    df['implausible_phenoage'] = np.where(implausible_mask, 1, 0)

    # แสดงรายงานสรุปผลจริง
    print("\n" + "=" * 45)
    print("PHASE 3 SUMMARY REPORT (SUCCESS)")
    print("=" * 45)
    print(f"  Total participants:               {len(df):,}")
    print(f"  Mean Chronological Age (อายุจริง):  {df['age'].mean():.2f} ปี")
    print(f"  Mean Phenotypic Age (อายุชีวภาพ):  {df['PhenotypicAge'].mean():.2f} ปี")
    print(f"  Mean PhenoAge Gap (ส่วนต่างอายุ):   {df['PhenoAge_gap'].mean():.2f} ปี")
    print(f"  Implausible Cases Flagged:        {implausible_mask.sum()} ราย")
    print("=" * 45)

    df.to_csv(OUTPUT_CSV, index=False)
    print(f"\nSuccess! File saved to: {OUTPUT_CSV}")